# Generated by Django 4.2 on 2023-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="property_photos"),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
