# Generated by Django 4.2.1 on 2023-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_property_address_alter_property_bathrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
